@file:Suppress("unused")

package cc.lapiz.solstice.input

data class Key(val name: String)

object Keys {
	var SPACE = Key("SPACE")
	var APOSTROPHE = Key("APOSTROPHE")
	var COMMA = Key("COMMA")
	var MINUS = Key("MINUS")
	var PERIOD = Key("PERIOD")
	var SLASH = Key("SLASH")
	var NUM_0 = Key("NUM_0")
	var NUM_1 = Key("NUM_1")
	var NUM_2 = Key("NUM_2")
	var NUM_3 = Key("NUM_3")
	var NUM_4 = Key("NUM_4")
	var NUM_5 = Key("NUM_5")
	var NUM_6 = Key("NUM_6")
	var NUM_7 = Key("NUM_7")
	var NUM_8 = Key("NUM_8")
	var NUM_9 = Key("NUM_9")
	var SEMICOLON = Key("SEMICOLON")
	var EQUAL = Key("EQUAL")
	var A = Key("A")
	var B = Key("B")
	var C = Key("C")
	var D = Key("D")
	var E = Key("E")
	var F = Key("F")
	var G = Key("G")
	var H = Key("H")
	var I = Key("I")
	var J = Key("J")
	var K = Key("K")
	var L = Key("L")
	var M = Key("M")
	var N = Key("N")
	var O = Key("O")
	var P = Key("P")
	var Q = Key("Q")
	var R = Key("R")
	var S = Key("S")
	var T = Key("T")
	var U = Key("U")
	var V = Key("V")
	var W = Key("W")
	var X = Key("X")
	var Y = Key("Y")
	var Z = Key("Z")
	var LEFT_BRACKET = Key("LEFT_BRACKET")
	var BACKSLASH = Key("BACKSLASH")
	var RIGHT_BRACKET = Key("RIGHT_BRACKET")
	var ESCAPE = Key("ESCAPE")
	var ENTER = Key("ENTER")
	var TAB = Key("TAB")
	var BACKSPACE = Key("BACKSPACE")
	var INSERT = Key("INSERT")
	var DELETE = Key("DELETE")
	var RIGHT = Key("RIGHT")
	var LEFT = Key("LEFT")
	var DOWN = Key("DOWN")
	var UP = Key("UP")
	var PAGE_UP = Key("PAGE_UP")
	var PAGE_DOWN = Key("PAGE_DOWN")
	var HOME = Key("HOME")
	var END = Key("END")
	var PAUSE = Key("PAUSE")
	var F1 = Key("F1")
	var F2 = Key("F2")
	var F3 = Key("F3")
	var F4 = Key("F4")
	var F5 = Key("F5")
	var F6 = Key("F6")
	var F7 = Key("F7")
	var F8 = Key("F8")
	var F9 = Key("F9")
	var F10 = Key("F10")
	var F11 = Key("F11")
	var F12 = Key("F12")
	var SHIFT = Key("SHIFT")
	var CONTROL = Key("CONTROL")
	var ALT = Key("ALT")
	var SUPER = Key("SUPER")
	var MENU = Key("MENU")
}